FROM apache/airflow:2.10.4-python3.12

USER root
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

USER airflow
COPY pyproject.toml README.md /opt/airflow/
RUN uv pip install --no-cache /opt/airflow/

COPY src/ /opt/airflow/src/
COPY airflow_dev/dags/ /opt/airflow/dags/

EXPOSE 8080
