# NodePort : expose la WebApp sur http://localhost:30860 (ou <minikube-ip>:30860)
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: wholesale-mlops
spec:
  selector:
    app: webapp
  ports:
    - port: 7860
      targetPort: 7860
      nodePort: 30860
  type: NodePort
